<?php

$from = 'collageme<support@collageme.com>';

$messagei = '<html><body style="background:#fff;color:#000;"><div style="background: #fff;
position: absolute;top: 0;left: 0;right: 0;height: 100%;">';
$messagei .= '<header style="padding:30px 20px;text-align:center;"><img src="https://collageme.com/assets/images/logo_2.png" alt="Company logo" style="width:180px;height:75px;display:block;margin:0 auto;" /></header><br/>';
$messagei .= '<div style="padding: 18px 20px;"><div style="color:black;font-size:.9em;padding:20px;margin: auto;background: lightgrey;color:#000;">' . $message . '</div></div>';
$messagei .= '
<br/>
<div style="padding: 80px 30px;background:#000;color:#fff;text-align:center;">
<p style="margin-bottom: 5px;">For inquires contact us on our official email <a href="mailto:' . $from . '">' . $from . '</a></p><br/>
<small>Thank you for choosing collageme company.<br/>Best Regards.
</small>
<a style="margin:80px auto 30px; auto;" href="https://www.collageme.com">Visit Website</a>
</div></div>';
$messagei .= '</body></html>';


// $messagei = '<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"> <meta name="viewport" content="width=device-width, initial-scale=1.0"> <meta name="x-apple-disable-message-reformatting"><meta http-equiv="X-UA-Compatible" content="IE=edge"><!--<![endif]--><title></title> <style type="text/css"> @media only screen and (min-width: 620px) {.u-row {width: 600px !important;}.u-row .u-col {vertical-align: top;}.u-row .u-col-100 {width: 600px !important;}}@media (max-width: 620px) {.u-row-container {max-width: 100% !important;padding-left: 0px !important;padding-right: 0px !important;}.u-row .u-col {min-width: 320px !important;max-width: 100% !important;display: block !important;}.u-row {width: 100% !important;}.u-col {width: 100% !important;}.u-col > div {margin: 0 auto;}}body {margin: 0;padding: 0;}table,tr,td {vertical-align: top;border-collapse: collapse;}p {margin: 0;}.ie-container table,.mso-container table {table-layout: fixed;}* {line-height: inherit;}a[x-apple-data-detectors=\'true\'] {color: inherit !important;text-decoration: none !important;}@media (max-width: 480px) {.hide-mobile {max-height: 0px;overflow: hidden;display: none !important;}}table, td { color: #000000; } #u_body a { color: #0000ee; text-decoration: underline; } @media (max-width: 480px) { #u_content_image_3 .v-src-width { width: auto !important; } #u_content_image_3 .v-src-max-width { max-width: 100% !important; } #u_content_heading_2 .v-font-size { font-size: 17px !important; } #u_content_text_deprecated_1 .v-container-padding-padding { padding: 40px 10px !important; } #u_content_text_deprecated_1 .v-line-height { line-height: 180% !important; } #u_content_text_deprecated_3 .v-container-padding-padding { padding: 40px 10px 10px !important; } #u_content_menu_1 .v-padding { padding: 5px 10px !important; } }</style>';
// $messagei .= '<!--[if !mso]><!--><link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700&amp;display=swap" rel="stylesheet" type="text/css"><link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700&amp;display=swap" rel="stylesheet" type="text/css"><link href="https://fonts.googleapis.com/css2?family=Arvo&amp;display=swap" rel="stylesheet" type="text/css"><!--<![endif]--><table id="u_body" style="border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;min-width: 320px;Margin: 0 auto;background-color: #e7e7e7;width:100%" cellpadding="0" cellspacing="0"><tbody><tr style="vertical-align: top"><td style="word-break: break-word;border-collapse: collapse !important;vertical-align: top"><div class="u-row-container" style="padding: 0px;background-color: transparent"><div class="u-row" style="margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: transparent;"><div style="border-collapse: collapse;display: table;width: 100%;height: 100%;background-color: transparent;"><div class="u-col u-col-100" style="max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;"><div style="background-color: #ffffff;height: 100%;width: 100% !important;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;"><!--[if (!mso)&(!IE)]><!--><div style="box-sizing: border-box; height: 100%; padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;"><!--<![endif]-->';
// $messagei .= '<table id="u_content_image_3" style="font-family:\'Open Sans\',sans-serif;" role="presentation" cellpadding="0" cellspacing="0" width="100%" border="0"><tbody><tr> <td class="v-container-padding-padding" style="overflow-wrap:break-word;word-break:break-word;padding:40px 10px;font-family:\'Open Sans\',sans-serif;" align="left">   <table width="100%" cellpadding="0" cellspacing="0" border="0"><tbody><tr><td style="padding-right: 0px;padding-left: 0px;" align="center">  <img align="center" border="0" src="https://collageme.com/assets/images/logo_2.png" alt="image" title="image" style="outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: inline-block !important;border: none;height: auto;float: none;width: 75%;max-width: 100px;" width="100" class="v-src-width v-src-max-width"> </td></tr></tbody></table> </td></tr></tbody></table></div></div>';
// $messagei .= '</div></div></div><div class="u-row-container" style="padding: 0px;background-color: transparent"><div class="u-row" style="margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: transparent;"><div style="border-collapse: collapse;display: table;width: 100%;height: 100%;background-color: transparent;"><div class="u-col u-col-100" style="max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;"><div style="background-color: #f5f5f5;height: 100%;width: 100% !important;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;"><div style="box-sizing: border-box; height: 100%; padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;">';
// $messagei .= '<table id="u_content_heading_2" style="font-family:\'Open Sans\',sans-serif;" role="presentation" cellpadding="0" cellspacing="0" width="100%" border="0"><tbody><tr> <td class="v-container-padding-padding" style="overflow-wrap:break-word;word-break:break-word;padding:40px 10px 0px;font-family:\'Open Sans\',sans-serif;" align="left">   <h1 class="v-line-height v-font-size" style="margin: 0px; color: #000000; line-height: 140%; text-align: center; word-wrap: break-word; font-family: Arvo; font-size: 22px; font-weight: 400;">';
// $messagei .= '<strong>Hello</strong></h1> </td></tr></tbody></table><table id="u_content_text_deprecated_1" style="font-family:\'Open Sans\',sans-serif;" role="presentation" cellpadding="0" cellspacing="0" width="100%" border="0"><tbody><tr> <td class="v-container-padding-padding" style="overflow-wrap:break-word;word-break:break-word;padding:40px 30px;font-family:\'Open Sans\',sans-serif;" align="left">   <div class="v-line-height v-font-size" style="font-size: 14px; line-height: 180%; text-align: justify; word-wrap: break-word;"><p style="line-height: 180%; font-size: 14px;"><br><div><div style="font-family: Montserrat, sans-serif;"> '. $message;
// $messagei .= '</div></div></p><p style="line-height: 180%; font-size: 14px;">&nbsp;</p><p style="line-height: 180%; font-size: 14px;"><span style="font-size: 14px; line-height: 25.2px;">collageme Team</span></p></div> </td></tr></tbody></table></div></div></div></div></div><div class="u-row-container" style="padding: 0px;background-color: transparent"><div class="u-row" style="margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: transparent;"><div style="border-collapse: collapse;display: table;width: 100%;height: 100%;background-color: transparent;"><div class="u-col u-col-100" style="max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;"><div style="height: 100%;width: 100% !important;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;"><!--[if (!mso)&(!IE)]><!--><div style="box-sizing: border-box; height: 100%; padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;"><!--<![endif]--><table id="u_content_text_deprecated_3" style="font-family:\'Open Sans\',sans-serif;" role="presentation" cellpadding="0" cellspacing="0" width="100%" border="0">';
// $messagei .= '<tbody><tr> <td class="v-container-padding-padding" style="overflow-wrap:break-word;word-break:break-word;padding:40px 80px 10px;font-family:\'Open Sans\',sans-serif;" align="left">   <div class="v-line-height v-font-size" style="font-size: 14px; line-height: 160%; text-align: center; word-wrap: break-word;"><p style="font-size: 14px; line-height: 160%;">if you have any questions, please email us at <a rel="noopener" href="https://collageme.com/" target="_blank">info@collageme.com</a> or visit our FAQS, you can also chat with a reel live human during our operating hours. They can answer questions about your account</p></div> </td></tr></tbody></table><table style="font-family:\'Open Sans\',sans-serif;" role="presentation" cellpadding="0" cellspacing="0" width="100%" border="0"><tbody><tr> <td class="v-container-padding-padding" style="overflow-wrap:break-word;word-break:break-word;padding:20px 0px;font-family:\'Open Sans\',sans-serif;" align="left">   <table height="0px" align="center" border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;border-top: 1px solid #BBBBBB;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%"><tbody> <tr style="vertical-align: top">   <td style="word-break: break-word;border-collapse: collapse !important;vertical-align: top;font-size: 0px;line-height: 0px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%">     <span>&nbsp;</span>   </td> </tr></tbody></table> </td></tr>';
// $messagei .= '</tbody></table><table style="font-family:\'Open Sans\',sans-serif;" role="presentation" cellpadding="0" cellspacing="0" width="100%" border="0"><tbody><tr> <td class="v-container-padding-padding" style="overflow-wrap:break-word;word-break:break-word;padding:10px;font-family:\'Open Sans\',sans-serif;" align="left">   <div align="center"><div style="display: table; max-width:187px;"><!--[if (mso)|(IE)]></td><![endif]--><!--[if (mso)|(IE)]><td width="32" style="width:32px; padding-right: 15px;" valign="top"><![endif]--> <!--[if (mso)|(IE)]></td><![endif]--><!--[if (mso)|(IE)]><td width="32" style="width:32px; padding-right: 0px;" valign="top"><![endif]--><!--[if (mso)|(IE)]></td><![endif]--><!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]--></div></div> </td></tr></tbody></table><table id="u_content_menu_1" style="font-family:\'Open Sans\',sans-serif;" role="presentation" cellpadding="0" cellspacing="0" width="100%" border="0"><tbody><tr> <td class="v-container-padding-padding" style="overflow-wrap:break-word;word-break:break-word;padding:10px;font-family:\'Open Sans\',sans-serif;" align="left">   <div class="menu" style="text-align:center"><!--[if (mso)|(IE)]><table role="presentation" border="0" cellpadding="0" cellspacing="0" align="center"><tr><![endif]--><!--[if (mso)|(IE)]><td style="padding:5px 15px"><![endif]-->';
// $messagei .= '<a href="https://collageme.com/" target="_self" style="padding:5px 15px;display:inline-block;color:#000000;font-size:14px;text-decoration:none" class="v-padding v-font-size"> Home</a><span style="padding:5px 15px;display:inline-block;color:#000000;font-size:14px;" class="v-padding v-font-size hide-mobile"> |</span><a href="https://collageme.com/market.php" target="_self" style="padding:5px 15px;display:inline-block;color:#000000;font-size:14px;text-decoration:none" class="v-padding v-font-size"> Market</a><span style="padding:5px 15px;display:inline-block;color:#000000;font-size:14px;" class="v-padding v-font-size hide-mobile"> |</span><a href="https://collageme.com/about.php" target="_self" style="padding:5px 15px;display:inline-block;color:#000000;font-size:14px;text-decoration:none" class="v-padding v-font-size"> About Us</a><span style="padding:5px 15px;display:inline-block;color:#000000;font-size:14px;" class="v-padding v-font-size hide-mobile"> |</span><a href="https://collageme.com/" target="_self" style="padding:5px 15px;display:inline-block;color:#000000;font-size:14px;text-decoration:none" class="v-padding v-font-size"> Contact US</a>';
// $messagei .= '</div> </td></tr></tbody></table><table style="font-family:\'Open Sans\',sans-serif;" role="presentation" cellpadding="0" cellspacing="0" width="100%" border="0"><tbody><tr> <td class="v-container-padding-padding" style="overflow-wrap:break-word;word-break:break-word;padding:10px 10px 40px;font-family:\'Open Sans\',sans-serif;" align="left">   <div class="v-line-height v-font-size" style="font-size: 14px; line-height: 160%; text-align: center; word-wrap: break-word;"><p style="font-size: 14px; line-height: 160%;">you have received this email as a registered user of <a rel="noopener" href="./register.html" target="_blank">collageme</a></p><p style="font-size: 14px; line-height: 160%;">&nbsp;</p>';
// $messagei .= '<p style="font-size: 14px; line-height: 160%;">collageme All rights reserved</p></div> </td></tr></tbody></table><!--[if (!mso)&(!IE)]><!--></div><!--<![endif]--></div></div><!--[if (mso)|(IE)]></td><![endif]--> <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]--></div></div></div><!--[if (mso)|(IE)]></td></tr></table><![endif]--></div></div></td></tr></tbody></table><!--[if mso]></div><![endif]--><!--[if IE]></div><![endif]-->';

//echo $messagei;
// Thanks For joining us.<br></div><div style="font-family: Montserrat, sans-serif;">Please use the below code to verify your email address.<br></div><div style="font-family: Montserrat, sans-serif;"><br></div><div style="font-family: Montserrat, sans-serif;">Your email verification code is:<font size="6"><span style="font-weight: bolder;">&nbsp;839339</span></font>
?>